CREATE TABLE Categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE NOT NULL,
    description VARCHAR2(255)
);

CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    is_verified NUMBER(1) DEFAULT 0 CHECK (is_verified IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Memes (
    meme_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    category_id NUMBER,
    title VARCHAR2(255) NOT NULL,
    image_url VARCHAR2(1000) NOT NULL,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_memes_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_memes_category FOREIGN KEY (category_id) REFERENCES Categories(category_id) ON DELETE SET NULL
);

CREATE TABLE OTP_Logs (
    otp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL,
    otp_code VARCHAR2(10) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    is_used NUMBER(1) DEFAULT 0 CHECK (is_used IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_otp_email FOREIGN KEY (email) REFERENCES Users(email) ON DELETE CASCADE
);

CREATE TABLE Activity_Logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    action VARCHAR2(100) NOT NULL,
    details CLOB,
    log_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

INSERT INTO Categories (name, description) VALUES ('Dank Memes', 'The dankest of the dank.');
INSERT INTO Categories (name, description) VALUES ('Wholesome', 'Memes that make you smile.');
INSERT INTO Categories (name, description) VALUES ('Programming', 'Relatable dev struggles.');
INSERT INTO Categories (name, description) VALUES ('Animals', 'Funny pets and wildlife.');
INSERT INTO Categories (name, description) VALUES ('Funny', 'Generally funny memes.');
INSERT INTO Categories (name, description) VALUES ('Coding', 'Code-related humor.');
INSERT INTO Categories (name, description) VALUES ('Gaming', 'Game-related memes.');
INSERT INTO Categories (name, description) VALUES ('Sports', 'Sports memes.');
COMMIT;

CREATE TABLE Likes (
    like_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    meme_id NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_meme FOREIGN KEY (meme_id) REFERENCES Memes(meme_id) ON DELETE CASCADE,
    CONSTRAINT uq_likes UNIQUE (user_id, meme_id)
);

CREATE TABLE Comments (
    comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    meme_id NUMBER NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_meme FOREIGN KEY (meme_id) REFERENCES Memes(meme_id) ON DELETE CASCADE
);

-- ============ MIGRATION: Phase 3 — Multi-format Memes ============
-- Run these statements manually on existing databases:
-- ALTER TABLE Memes ADD meme_type VARCHAR2(10) DEFAULT 'image';
-- ALTER TABLE Memes MODIFY image_url VARCHAR2(1000) NULL;
